In [1]:
#import numpy
import numpy as np

In [2]:
# create a 1-D numpy array
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [3]:
# create a 2-D numpy array
# 2 square brackets will be used
arr2 = np.array([[1,3,5,7],[2,4,6,8]])
print(arr2)

[[1 3 5 7]
 [2 4 6 8]]


In [4]:
# To find type of array
type(arr2)

numpy.ndarray

In [5]:
# to find the dimensions of an array
print("dimensions of arr1 is ",arr1.ndim)
print("dimensions of arr2 is ",arr2.ndim)

dimensions of arr1 is  1
dimensions of arr2 is  2


In [6]:
# to find the size of an array
print("size of arr1 is ",arr1.size)
print("size of arr2 is ",arr2.size)

size of arr1 is  4
size of arr2 is  8


In [7]:
# to find number of rows and columns in an array
# in the format of (rows,columns) 
print("shape of arr1 is ",arr1.shape)
print("shape of arr2 is ",arr2.shape)

shape of arr1 is  (4,)
shape of arr2 is  (2, 4)


In [8]:
# to create a 1D array with each element as 0
# to create a 1D array with each element as 1
arr1 = np.zeros(5)
arr2 = np.ones(5)
print("Array with each element initialized as 0 of float type: ",arr1)
print("Array with each element initialized as 1 of float type: ",arr2)

Array with each element initialized as 0 of float type:  [0. 0. 0. 0. 0.]
Array with each element initialized as 1 of float type:  [1. 1. 1. 1. 1.]


In [9]:
# to create a 2D array with each element as 0
# to create a 2D array with each element as 1
arr1 = np.zeros((3,3))
arr2 = np.ones((3,3))
print("\nArray with each element initialized as 0 of float type: \n",arr1)
print("\nArray with each element initialized as 1 of float type: \n",arr2)


Array with each element initialized as 0 of float type: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array with each element initialized as 1 of float type: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# to create an array of zeros of int type
# to create an array of ones of int type
arr1 = np.zeros((3,3),dtype = int)
arr2 = np.ones((3,3),dtype = int)
print("\nArray with each element initialized as 0 of int type: \n",arr1)
print("\nArray with each element initialized as 1 of int type: \n",arr2)


Array with each element initialized as 0 of int type: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Array with each element initialized as 1 of int type: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
# to create an array of zeros of bool type
# to create an array of ones of bool type
arr1 = np.zeros((3,3),dtype = bool)
arr2 = np.ones((3,3),dtype = bool)
print("\nArray with each element initialized as 0 of bool type: \n",arr1)
print("\nArray with each element initialized as 1 of bool type: \n",arr2)


Array with each element initialized as 0 of bool type: 
 [[False False False]
 [False False False]
 [False False False]]

Array with each element initialized as 1 of bool type: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [12]:
# to convert 1D array to 2 dimensional array 
arr1 = np.arange(1,13)
arr1 = arr1.reshape(3,4)
print("2D array: \n",arr1)
arr2 = np.arange(1,21)
arr2 = arr2.reshape(2,10)
print("2D array: \n",arr2)

2D array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2D array: 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [13]:
# to convert 1D array to 3D array
arr1 = np.ones(15,dtype = int)
arr1 = arr1.reshape(5,3,1)
print("3D - Array \n",arr1)
arr2 = np.zeros(12,dtype = int)
arr2 = arr2.reshape(3,2,2)
print("\n3D - Array \n",arr2)

3D - Array 
 [[[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]]

3D - Array 
 [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [14]:
# Multidimensional array to 1-Dimensional array
print("3D Array to 1D array: ",arr1.ravel())
print("3D array to 1D array: ",arr2.ravel())

3D Array to 1D array:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
3D array to 1D array:  [0 0 0 0 0 0 0 0 0 0 0 0]


In [15]:
# Calculate transpose of a matrix
arr1 = np.ones(30,dtype = int)
arr1 = arr1.reshape(3,2,5)
arr2 = np.zeros((3,4),dtype = int)
print("3D array:\n",arr1,"\n\nTranspose:\n",arr1.transpose(),
      "\n\n2D array:\n",arr2,"\nTranspose: \n",arr2.transpose())


3D array:
 [[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]] 

Transpose:
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]] 

2D array:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 
Transpose: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
# Various operations that can be performed using numpy
arr1 = np.arange(1,18,2).reshape(3,3)
arr2 = np.arange(2,19,2).reshape(3,3)
print(arr1,"\n\n",arr2)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]] 

 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [17]:
#Addition
print("Sum of array1 and array2: \n",arr1+arr2)
#Substraction
print("\nDifference between array1 and array2: \n",arr2 - arr1)
#Division
print("\nDivision of array1 and array2: \n",arr2/arr1)
#Multiplication of each element of one matrix to another
print("\nMultiplication of array1 and array2 element by element: \n",arr1*arr2)
#Matrix multiplication
print("\nMatrix multiplication of arr1 and arr2: \n",arr1@arr2)

Sum of array1 and array2: 
 [[ 3  7 11]
 [15 19 23]
 [27 31 35]]

Difference between array1 and array2: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Division of array1 and array2: 
 [[2.         1.33333333 1.2       ]
 [1.14285714 1.11111111 1.09090909]
 [1.07692308 1.06666667 1.05882353]]

Multiplication of array1 and array2 element by element: 
 [[  2  12  30]
 [ 56  90 132]
 [182 240 306]]

Matrix multiplication of arr1 and arr2: 
 [[ 96 114 132]
 [240 294 348]
 [384 474 564]]


In [18]:
# Find maximum value element in a matrix
print("Largest value in arr1: ",arr1.max(),"\nLargest value in arr2: ",arr2.max())
# Find minimum value element in a matrix
print("\nSmallest value in arr1: ",arr1.min(),"\nSmallest value in arr2: ",arr2.min())
# Find index of the maximum value element in a matrix
print("\nIndex of the largest element in a arr1: ",arr1.argmax(),
      "\nIndex of the largest element in arr2: ",arr2.argmax())
# Find index of the minimum value element in a matrix
print("\nIndex of the smallest element in a arr1: ",arr1.argmin(),
      "\nIndex of the smallest element in arr2: ",arr2.argmin())
#Find maximum value element in a matrix for a particular column(for column use axis = 0)
print("\nLargest element for each column of arr1: ",arr1.max(axis = 0))
print("Largest element for each column of arr2: ",arr2.max(axis = 0))
#Find minimum value element in a matrix for a particular column(for column use axis = 0)
print("\nSmallest element for each column of arr1: ",arr1.min(axis = 0))
print("Smallest element for each column of arr2: ",arr2.min(axis=0))
# Find the maximum element in a matrix for a particular row(for row use axis = 1)
print("\nLargest element for each row of arr1: ",arr1.max(axis = 1))
print("Largest element for each row of arr2: ",arr2.max(axis = 1))
# Find the minimum element in a matrix for a particular row(for row use axis = 1)
print("\nSmallest element for each row of arr1: ",arr1.min(axis = 1))
print("Smallest element for each row of arr2: ",arr2.min(axis = 1))


Largest value in arr1:  17 
Largest value in arr2:  18

Smallest value in arr1:  1 
Smallest value in arr2:  2

Index of the largest element in a arr1:  8 
Index of the largest element in arr2:  8

Index of the smallest element in a arr1:  0 
Index of the smallest element in arr2:  0

Largest element for each column of arr1:  [13 15 17]
Largest element for each column of arr2:  [14 16 18]

Smallest element for each column of arr1:  [1 3 5]
Smallest element for each column of arr2:  [2 4 6]

Largest element for each row of arr1:  [ 5 11 17]
Largest element for each row of arr2:  [ 6 12 18]

Smallest element for each row of arr1:  [ 1  7 13]
Smallest element for each row of arr2:  [ 2  8 14]


In [19]:
# To find the sum of each element in a matrix
print("Sum of arr1: ",np.sum(arr1),"\nSum of arr2: ",np.sum(arr2))
# To find the sum of each element in a row of a matrix
print("\nSum of each row of arr1: ",np.sum(arr1,axis = 1),"\nSum of each row of arr2: ",np.sum(arr2,axis = 1))
# To print sum of each element in a column of a matrix
print("\nSum of each column of arr1: ",np.sum(arr1,axis=0),"\nSum of each column of arr2: ",np.sum(arr2,axis = 0))

Sum of arr1:  81 
Sum of arr2:  90

Sum of each row of arr1:  [ 9 27 45] 
Sum of each row of arr2:  [12 30 48]

Sum of each column of arr1:  [21 27 33] 
Sum of each column of arr2:  [24 30 36]


In [20]:
#To find mean of a matrix
print("Mean of arr1: ",np.mean(arr1),"\nMean of arr2: ",np.mean(arr2))
# To find mean of each row in a matrix
print("\nMean of each row of arr1: ",np.mean(arr1,axis = 1,dtype = int),
      "\nMean of each row of arr2: ",np.mean(arr2,axis=1,dtype = int))
# To print mean of each column in a matrix
print("\nMean of each column of arr1: ",np.mean(arr1,axis=0,dtype=int),
     "\nMean of each column of arr2: ",np.mean(arr2,axis = 0,dtype = int))

Mean of arr1:  9.0 
Mean of arr2:  10.0

Mean of each row of arr1:  [ 3  9 15] 
Mean of each row of arr2:  [ 4 10 16]

Mean of each column of arr1:  [ 7  9 11] 
Mean of each column of arr2:  [ 8 10 12]


In [21]:
# Find the square root of each element in an array
print("Square root of each element of arr1: \n",np.sqrt(arr1))
print("\nSquare root of each element of arr2: \n",np.sqrt(arr2))

Square root of each element of arr1: 
 [[1.         1.73205081 2.23606798]
 [2.64575131 3.         3.31662479]
 [3.60555128 3.87298335 4.12310563]]

Square root of each element of arr2: 
 [[1.41421356 2.         2.44948974]
 [2.82842712 3.16227766 3.46410162]
 [3.74165739 4.         4.24264069]]


In [22]:
# Finding exponent of each element in an array
print("Exponent of each element of arr1: \n",np.exp(arr1))
print("Exponent of each element of arr2: \n",np.exp(arr2))

Exponent of each element of arr1: 
 [[2.71828183e+00 2.00855369e+01 1.48413159e+02]
 [1.09663316e+03 8.10308393e+03 5.98741417e+04]
 [4.42413392e+05 3.26901737e+06 2.41549528e+07]]
Exponent of each element of arr2: 
 [[7.38905610e+00 5.45981500e+01 4.03428793e+02]
 [2.98095799e+03 2.20264658e+04 1.62754791e+05]
 [1.20260428e+06 8.88611052e+06 6.56599691e+07]]


In [23]:
#Find natural log for each element in an array
print("Natural log of each element of arr1: \n",np.log(arr1))
print("Natural log of each element of arr2: \n",np.log(arr2))

Natural log of each element of arr1: 
 [[0.         1.09861229 1.60943791]
 [1.94591015 2.19722458 2.39789527]
 [2.56494936 2.7080502  2.83321334]]
Natural log of each element of arr2: 
 [[0.69314718 1.38629436 1.79175947]
 [2.07944154 2.30258509 2.48490665]
 [2.63905733 2.77258872 2.89037176]]


In [24]:
#Find log base 10 for each element in an array
print("Log base 10 for each element in arr1: \n",np.log10(arr1))
print("Log base 10 for each element in arr2: \n",np.log10(arr2))

Log base 10 for each element in arr1: 
 [[0.         0.47712125 0.69897   ]
 [0.84509804 0.95424251 1.04139269]
 [1.11394335 1.17609126 1.23044892]]
Log base 10 for each element in arr2: 
 [[0.30103    0.60205999 0.77815125]
 [0.90308999 1.         1.07918125]
 [1.14612804 1.20411998 1.25527251]]


In [25]:
#Create an array and use slicing function in it
arr1 = np.arange(1,101).reshape(10,10)
#Various methods of printing the whole array
print(arr1,"\n\n",arr1[:],"\n\n",arr1[::],"\n\n",arr1[:,:])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]] 

 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]] 

 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 

In [26]:
#Slicing an array to get first row of the array
print(arr1[0:1,:])
#Slicing an array to get last column of the array
print("\n",arr1[:,9:10])
#Slice an array 
print("\n",arr1[3:5,3:5])
# Slice a single element in the form of scalar
print("\n",arr1[6,8]," dimensions==> ",arr1[6,8].ndim)
#Slice a single element in the form of a 2D 
print("\n",arr1[6:7,8:9],"dimensions==> ",arr1[6:7,8:9].ndim)

[[ 1  2  3  4  5  6  7  8  9 10]]

 [[ 10]
 [ 20]
 [ 30]
 [ 40]
 [ 50]
 [ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]]

 [[34 35]
 [44 45]]

 69  dimensions==>  0

 [[69]] dimensions==>  2


In [27]:
# Concatenation of two numpy arrays
arr1 = np.arange(1,32,2).reshape(4,4)
arr2 = np.arange(2,34,2).reshape(4,4)
#method 1:
print("Using concatenate function\n")
print("Default concatenate(column wise)\n",np.concatenate((arr1,arr2)))
print("\nRow wise concatenation\n",np.concatenate((arr1,arr2),axis=1))
#method 2:
print("\n\nUsing vstack or hstack function\n")
print("Column wise concatenation\n",np.vstack((arr1,arr2)))
print("\nRow wise concatenation\n",np.hstack((arr1,arr2)))

Using concatenate function

Default concatenate(column wise)
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Row wise concatenation
 [[ 1  3  5  7  2  4  6  8]
 [ 9 11 13 15 10 12 14 16]
 [17 19 21 23 18 20 22 24]
 [25 27 29 31 26 28 30 32]]


Using vstack or hstack function

Column wise concatenation
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Row wise concatenation
 [[ 1  3  5  7  2  4  6  8]
 [ 9 11 13 15 10 12 14 16]
 [17 19 21 23 18 20 22 24]
 [25 27 29 31 26 28 30 32]]


In [28]:
#Use split function to split an array into 4 parts
print(np.split(arr1,4))
# When we split an array it gets compressed into a list
print("\n",type(np.split(arr1,4)))
#Use split fi=unction to split an array vertically into 4 parts
print("\n",np.split(arr1,4,axis = 1))
#Use split function to split an array into 3 parts
print("\n",np.split(arr1,[2,3],axis=1))

[array([[1, 3, 5, 7]]), array([[ 9, 11, 13, 15]]), array([[17, 19, 21, 23]]), array([[25, 27, 29, 31]])]

 <class 'list'>

 [array([[ 1],
       [ 9],
       [17],
       [25]]), array([[ 3],
       [11],
       [19],
       [27]]), array([[ 5],
       [13],
       [21],
       [29]]), array([[ 7],
       [15],
       [23],
       [31]])]

 [array([[ 1,  3],
       [ 9, 11],
       [17, 19],
       [25, 27]]), array([[ 5],
       [13],
       [21],
       [29]]), array([[ 7],
       [15],
       [23],
       [31]])]


In [47]:
#Create an array using random function
import random
print("1D array\n",np.random.random(3))
print("2D array\n",np.random.random((4,5)))
print("2D array with whole numbers as elements\n",np.random.randint(0,100,(3,3)))
print("3D array with whole number as element\n",np.random.randint(0,100,(2,3,3)))
print("2D array with positive and negative numbers as elements\n",np.random.randn(3,3))

1D array
 [0.34442968 0.78848845 0.28640974]
2D array
 [[0.10533266 0.1153123  0.02652191 0.97126495 0.65179335]
 [0.91849595 0.99654166 0.89298182 0.37373256 0.90288872]
 [0.02722049 0.45331119 0.1215341  0.22426197 0.71018528]
 [0.23658204 0.51158181 0.84879586 0.07786144 0.63251546]]
2D array with whole numbers as elements
 [[40 13 87]
 [52 72 78]
 [36  7 42]]
3D array with whole number as element
 [[[56 72 54]
  [62 93 98]
  [35 14 55]]

 [[84 18 63]
  [74 15 40]
  [ 9 45 73]]]
2D array with positive and negative numbers as elements
 [[-0.24972231 -0.40408516 -1.57830434]
 [ 0.47225721  0.16801902 -0.15387757]
 [-1.06863981 -0.73991034 -0.53515848]]
